name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or master, depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # or your preferred version

      - name: Install Dependencies
        run: npm install # or yarn install

      - name: Build
        run: npm run build # or yarn build
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_AUTH_KEY: ${{ secrets.VITE_AUTH_KEY }}
          VITE_ALL_STATIONS_KEY: ${{ vars.VITE_ALL_STATIONS_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # or your build output directory
          branch: gh-pages
